from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView
from .views import (
    CoachTasksView,
    CoachTaskDetailView,
    EvidenceUploadView,
    TicketFileUploadView,
    EmailOrUsernameTokenObtainPairView,
    coach_wellbeing_dashboard,
    learner_wellbeing_report,
    coach_wellbeing_workflow,
    coach_options,
    create_support_ticket,
    support_tickets_list,
    update_support_ticket,
    archive_ticket,
    restore_ticket,
    archived_tickets_list,
    ticket_notes,
    ticket_evidence,
    ticket_survey_responses,
    onboarding_reports_list,
    onboarding_report_detail,
    onboarding_report_notes,
    onboarding_report_evidence,
    update_onboarding_report,
    archive_onboarding_report,
    restore_onboarding_report,
)
from accounts.booking_views import CreateBookingView, BookingDiagnosticView, BookingServicesView, BookingAvailabilityView, BookingFixServiceView, BookingTestCreateView, BookingPublishView, BookingStaffView

urlpatterns = [
    path("coaches/<str:coach_id>/tasks/", CoachTasksView.as_view()),
    path("coaches/<str:coach_id>/tasks/<str:task_id>/", CoachTaskDetailView.as_view()),
    path("evidence/upload/", EvidenceUploadView.as_view()),
    path("api/token/", EmailOrUsernameTokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("coach-wellbeing-dashboard/", coach_wellbeing_dashboard, name="coach-wellbeing-dashboard"),
    path("learner-wellbeing-report/<int:learner_id>/", learner_wellbeing_report, name="learner-wellbeing-report"),
    path("coach-wellbeing-workflow/", coach_wellbeing_workflow, name="coach-wellbeing-workflow"),
    path("coach-options/", coach_options, name="coach-options"),
    path("support-tickets/", create_support_ticket, name="support-tickets"),
    path("support-tickets/list/", support_tickets_list, name="support-tickets-list"),
path("support-tickets/<int:ticket_id>/", update_support_ticket, name="update-support-ticket"),
    path("support-tickets/<int:ticket_id>/notes/", ticket_notes, name="ticket-notes"),
    path("support-tickets/<int:ticket_id>/evidence/", ticket_evidence, name="ticket-evidence"),
    path("support-tickets/<int:ticket_id>/survey-responses/", ticket_survey_responses, name="ticket-survey-responses"),
    path("support-tickets/<int:ticket_id>/archive/", archive_ticket, name="archive-ticket"),
    path("support-tickets/<int:ticket_id>/restore/", restore_ticket, name="restore-ticket"),
    path("support-tickets/archived/", archived_tickets_list, name="archived-tickets"),
    path("tickets/<int:ticket_id>/upload-file/", TicketFileUploadView.as_view(), name="ticket-file-upload"),
    path("bookings/appointments/", CreateBookingView.as_view(), name="create-booking"),
    path("bookings/services/", BookingServicesView.as_view(), name="booking-services"),
    path("bookings/staff/", BookingStaffView.as_view(), name="booking-staff"),
    path("bookings/availability/", BookingAvailabilityView.as_view(), name="booking-availability"),
    path("bookings/fix-service/", BookingFixServiceView.as_view(), name="booking-fix-service"),
    path("bookings/publish/", BookingPublishView.as_view(), name="booking-publish"),
    path("bookings/test-create/", BookingTestCreateView.as_view(), name="booking-test-create"),
    path("bookings/diagnostic/", BookingDiagnosticView.as_view(), name="booking-diagnostic"),
    path("onboarding-reports/", onboarding_reports_list, name="onboarding-reports"),
    path("onboarding-reports/<str:report_id>/", onboarding_report_detail, name="onboarding-report-detail"),
    path("onboarding-reports/<str:report_id>/notes/", onboarding_report_notes, name="onboarding-report-notes"),
    path("onboarding-reports/<str:report_id>/evidence/", onboarding_report_evidence, name="onboarding-report-evidence"),
    path("onboarding-reports/<str:report_id>/update/", update_onboarding_report, name="update-onboarding-report"),
    path("onboarding-reports/<str:report_id>/archive/", archive_onboarding_report, name="archive-onboarding-report"),
    path("onboarding-reports/<str:report_id>/restore/", restore_onboarding_report, name="restore-onboarding-report"),
]
