# Generated by Django 6.0.1 on 2026-02-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoachData',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('tasks', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'db_table': 'coaches_data',
                'managed': False,
            },
        ),
    ]
