# Generated by Django 6.0.1 on 2026-07-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_unmanaged_wellbeing_model_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coaches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MicrosoftConnection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('coach_id', models.BigIntegerField(unique=True)),
                ('microsoft_user_id', models.TextField(blank=True, null=True)),
                ('microsoft_email', models.TextField(blank=True, null=True)),
                ('tenant_id', models.TextField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_type', models.TextField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'microsoft_connections',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MicrosoftOAuthState',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('coach_id', models.BigIntegerField()),
                ('state', models.TextField()),
                ('redirect_uri', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'microsoft_oauth_states',
                'managed': False,
            },
        ),
    ]
