# Generated by Django 6.0.1 on 2026-10-07 14:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_support_ticket_coach_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='InclusionTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_report_id', models.TextField()),
                ('learner_id', models.BigIntegerField(blank=True, null=True)),
                ('learner_email', models.TextField()),
                ('learner_name', models.TextField(blank=True)),
                ('academic_email', models.TextField(blank=True)),
                ('previous_emails', models.TextField(blank=True)),
                ('programme', models.TextField(blank=True)),
                ('organization_name', models.TextField(blank=True)),
                ('coach_name', models.TextField(blank=True)),
                ('coach_email', models.TextField(blank=True)),
                ('manager_name', models.TextField(blank=True)),
                ('manager_email', models.TextField(blank=True)),
                ('subject', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('risk_level', models.CharField(max_length=20)),
                ('preferred_contact', models.CharField(default='email', max_length=10)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('incident_time', models.TimeField(blank=True, null=True)),
                ('created_by', models.TextField()),
                ('status', models.TextField(default='active')),
                ('progress_tier', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.JSONField(default=list)),
                ('evidence', models.JSONField(default=list)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inclusion_tickets',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
