# Generated by Django 6.0.1 on 2026-10-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_inclusion_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='inclusionticket',
            name='roster_learner_id',
            field=models.TextField(blank=True, db_index=True, default=''),
        ),
        migrations.AlterField(
            model_name='inclusionticket',
            name='source_report_id',
            field=models.TextField(blank=True),
        ),
    ]
